### ISSUE TITLE
Decryption taking too much time .

### ISSUE THREAD

**Issue by AnthonyJoshua1** [simbiose/Encryption#24]
Hi i am using this library to store values in shared pref , currently i'm using version 1.2.0 .
in my onCreate Method i'm getting values from sharedpref and after decryption i'm storing in variables . Now my problem is that Its taking too much time and also when i generate Signed APK with release build type , its returns Null in decyryptornull method .
Please help

**Comment by ademar111190** [comment]
Hi @AnthonyJoshua1 
I would like to have more details:
- How much is "much time"? Did you try to customize your instance with the `.setIterationCount`?
- Can you create a sample where this behaviour occurs on signed apks?

**Comment by AnthonyJoshua1** [comment]
Hi @ademar111190 
Thanks for responding , here is my case : 

- i have recently joined a team and they were using Simbio encryption v 1.2.0 , i have developed updated version of project and in OnCreate method of my activity i'm reading values from sharedpref and using  your decryption to decrypt sharedpref strings . when i start my activity which contains this code, it takes 2,3 seconds to start/load .

- i have to tried decryptsync callback too but time doesn't improve 
- when i updated library version to v2.1.0 performance did improve ,but its not decrypting v1.2.0 encrypted values and also setiteration count isn't working too .
it would mean alot if you help me out 
regards

**Comment by ademar111190** [comment]
I see, from version 1.x to 2.x I change the Iteration count, it is a breaking change, if you are using since version 1 you need to use the same iteration count, i.e. `.setIterationCount(65536)`. Set it on your builder before calling the build() method. Check the [Custom usage](https://github.com/simbiose/Encryption#custom-usage) for more info.


It should solve the problem of old encrypted strings. About the time spent to encrypt and decrypt it is the reason I changed from `.setIterationCount(65536)` to `.setIterationCount(1)` on versio 2.x in first place, as you can [see here](https://github.com/simbiose/Encryption/commit/f8923beeec1f03d0134a6a8c4167dc514259a776#diff-350ae885de5061c66bc4218b7ae544bbL356) the Iteration count is the main reason to take so long, unfortunatelly no solution for it :/

**Comment by AnthonyJoshua1** [comment]
Thankyou so much @ademar111190  , i have found the alternative solution about timing issue .
